# Generated by Django 5.1.1 on 2024-10-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='message',
        ),
    ]
